export const ADDED_SITE_SUCCESS = 'ADD_SITE_SUCCESS';
export const LOAD_SITES_SUCCESS = 'LOAD_SITES_SUCCESS';
export const START_AJAX_CALL = 'START_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const UPDATED_SITE_FILTERS = 'UPDATED_SITE_FILTERS';
